--------------------------------------------------------
--  File created - Четвъртък-Септември-27-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEVELOPERS
--------------------------------------------------------

  CREATE TABLE "IVELIN"."DEVELOPERS" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FEATURES
--------------------------------------------------------

  CREATE TABLE "IVELIN"."FEATURES" 
   (	"ID" NUMBER(8,0), 
	"SUMMARY" VARCHAR2(104 BYTE), 
	"OWNED_BY" VARCHAR2(27 BYTE), 
	"STATUS" VARCHAR2(15 BYTE), 
	"CHILDREN" VARCHAR2(300 BYTE), 
	"PARENT" NUMBER(6,0), 
	"FEATURE_SEQUENCE" NUMBER(2,0), 
	"BLOCKS" VARCHAR2(104 BYTE), 
	"ESTIMATE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLANNED_STORIES
--------------------------------------------------------

  CREATE TABLE "IVELIN"."PLANNED_STORIES" 
   (	"TYPE" VARCHAR2(26 BYTE), 
	"ID" NUMBER(8,0), 
	"SUMMARY" VARCHAR2(256 BYTE), 
	"USER_STORY_TECHNICAL_OWNER" VARCHAR2(128 BYTE), 
	"OWNED_BY" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(21 BYTE), 
	"MAINCOMPONENT" VARCHAR2(23 BYTE), 
	"ITERATION" VARCHAR2(18 BYTE), 
	"ADDITIONALEFFORT" VARCHAR2(5 BYTE), 
	"DEVELOPMENT_SEQUENCE" VARCHAR2(15 BYTE), 
	"PARENT" VARCHAR2(7 BYTE), 
	"BLOCKS" VARCHAR2(63 BYTE), 
	"SPRINT" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPRINTS
--------------------------------------------------------

  CREATE TABLE "IVELIN"."SPRINTS" 
   (	"SPRINT" VARCHAR2(26 BYTE), 
	"DEVELOPMENT_START" DATE, 
	"DEVELOPMENT_STOP" DATE, 
	"DEVELOPMENT_DAYS" NUMBER(26,0), 
	"DEVELOPERS" FLOAT(126), 
	"VACATION_SICKNESS" VARCHAR2(26 BYTE), 
	"CAPACITY" FLOAT(126), 
	"ACT_EFFORT" FLOAT(126), 
	"TARGET_FOCUS_FACTOR" FLOAT(126), 
	"ACTUAL__FOCUS_FACTOR" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STORIES
--------------------------------------------------------

  CREATE TABLE "IVELIN"."STORIES" 
   (	"TYPE" VARCHAR2(26 BYTE), 
	"ID" NUMBER(8,0), 
	"SUMMARY" VARCHAR2(256 BYTE), 
	"USER_STORY_TECHNICAL_OWNER" VARCHAR2(128 BYTE), 
	"OWNED_BY" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(21 BYTE), 
	"MAINCOMPONENT" VARCHAR2(23 BYTE), 
	"ITERATION" VARCHAR2(18 BYTE), 
	"ADDITIONALEFFORT" VARCHAR2(5 BYTE), 
	"DEVELOPMENT_SEQUENCE" VARCHAR2(15 BYTE), 
	"PARENT" VARCHAR2(7 BYTE), 
	"BLOCKS" VARCHAR2(63 BYTE), 
	"SPRINT" VARCHAR2(25 BYTE), 
	"ESTIMATE" NUMBER, 
	"PL_SPRINT" VARCHAR2(35 BYTE), 
	"PL_DEV" NUMBER(30,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TASKS
--------------------------------------------------------

  CREATE TABLE "IVELIN"."TASKS" 
   (	"TYPE" VARCHAR2(26 BYTE), 
	"ID" NUMBER(8,0), 
	"SUMMARY" VARCHAR2(256 BYTE), 
	"STATUS" VARCHAR2(13 BYTE), 
	"ITERATION" VARCHAR2(26 BYTE), 
	"PARENT" VARCHAR2(7 BYTE), 
	"ESTIMATEH" NUMBER(21,17), 
	"TIMESPEND" NUMBER(21,17)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEVLEOPERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IVELIN"."DEVLEOPERS_PK" ON "IVELIN"."DEVELOPERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FEATURES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IVELIN"."FEATURES_PK" ON "IVELIN"."FEATURES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPRINTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IVELIN"."SPRINTS_PK" ON "IVELIN"."SPRINTS" ("SPRINT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEVELOPERS
--------------------------------------------------------

  ALTER TABLE "IVELIN"."DEVELOPERS" ADD CONSTRAINT "DEVLEOPERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IVELIN"."DEVELOPERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "IVELIN"."DEVELOPERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FEATURES
--------------------------------------------------------

  ALTER TABLE "IVELIN"."FEATURES" ADD CONSTRAINT "FEATURES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IVELIN"."FEATURES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLANNED_STORIES
--------------------------------------------------------

  ALTER TABLE "IVELIN"."PLANNED_STORIES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPRINTS
--------------------------------------------------------

  ALTER TABLE "IVELIN"."SPRINTS" ADD CONSTRAINT "SPRINTS_PK" PRIMARY KEY ("SPRINT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IVELIN"."SPRINTS" MODIFY ("SPRINT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STORIES
--------------------------------------------------------

  ALTER TABLE "IVELIN"."STORIES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table STORIES
--------------------------------------------------------

  ALTER TABLE "IVELIN"."STORIES" ADD CONSTRAINT "STORIES_DEVELOPERS_FK1" FOREIGN KEY ("PL_DEV")
	  REFERENCES "IVELIN"."DEVELOPERS" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEVLEOPERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IVELIN"."DEVLEOPERS_TRG" 
  BEFORE INSERT ON DEVELOPERS
  FOR EACH ROW
  
  
BEGIN

 :new.ID := DEVLEOPERS_SEQ.nextval;

END;
/
ALTER TRIGGER "IVELIN"."DEVLEOPERS_TRG" DISABLE;
